package com.serverless.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.Data;

/**
 * Todoアイテムクラス
 */
@Data
@DynamoDBTable(tableName = "TodoItem")
public class TodoItem {

    /**
     * ID
     */
    @DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
    private String id;

    /**
     * タイトル
     */
    @DynamoDBAttribute(attributeName = "Title")
    private String title;

    /**
     * 内容
     */
    @DynamoDBAttribute(attributeName = "Contents")
    private String Contents;
}